#

# pern
#

CC = g++
LIBS = -g -Wall  -std=c++17

pern: dragon.o rider.o rdpair.o main.o
   $(CC) $(LIBS) -o pern dragon.o rider.o rdpair.o main.o

dragon.o : dragon.cpp
   $(CC) $(LIBS) -c dragon.cpp

main.o : main.cpp
   $(CC) $(LIBS) -c main.cpp

rider.o : rider.cpp
   $(CC) $(LIBS) -c rider.cpp

rdpair.o : rdpair.cpp
   $(CC) $(LIBS) -c rdpair.cpp

all : pern clean

clean:
   rm *.o
